media: public/images
content:
 - name: carte
   label: Carte
   path: data/carte.json
   type: file
   fields:
    - name: products
      label: Produits
      type: object
      list: true
      fields:
       - name: id
         type: number
       - name: title
         type: string
       - name: prix
         type: number
       - name: poids
         type: number
       - name: description
         type: text
       - name: images
         type: image
       - name: category
         type: select
         options:
           values: [
            'pain du mois',
            'pain courant',
            'pains spéciaux',
            'autres pains spéciaux',
            'farines anciennes, semences paysannes',
            'brioches',
            'viennoiseries',
            'apéritif',
            'autres gourmandises',
          ]
       - name: visible
         type: boolean