media: public/images
content:
  - name: carte
    label: Carte
    path: data/carte.json
    type: file
    fields:
      - name: products
        label: Produits
        type: object
        list: true
        fields:
          - name: id
            label: Id
            type: number
          - name: title
            label: Titre
            type: string
          - name: prix
            label: Prix
            type: number
          - name: poids
            label: Poids
            type: number
          - name: description
            label: Description
            type: text
          - name: images
            label: Images
            type: image
            input: public/images
            output: public/images
            options:
              path: public/images
              extensions: [ jpg, jpeg, png ]
          - name: category
            label: Catégorie
            type: select
            options:
              values:
                - pain du mois
                - pain courant
                - pains spéciaux
                - autres pains spéciaux
                - farines anciennes, semences paysannes
                - brioches
                - viennoiseries
                - apéritif
                - autres gourmandises
          - name: visible
            label: Visible
            type: boolean
