media: public/images
content:
  - name: carte
    label: Carte
    path: src/data/carte.json
    type: file
    format: json
    fields:
      - name: products
        label: Produits
        type: object
        list: true
        fields:
          - name: id
            label: Id
            type: number
          - name: title
            label: Titre
            type: string
          - name: prix
            label: Prix
            type: number
          - name: poids
            label: Poids
            type: number
          - name: description
            label: Description
            type: text
          - name: images
            label: Images
            type: image
            options:
              path: public/images/
              output: /
              extensions: [ jpg, jpeg, png ]
          - name: category
            label: Catégorie
            type: select
            options:
              values:
                - pain du mois
                - pain courant
                - pains spéciaux
                - autres pains spéciaux
                - farines anciennes, semences paysannes
                - brioches
                - viennoiseries
                - apéritif
                - autres gourmandises
          - name: visible
            label: Visible
            type: boolean
  - name: ateliers
    label: Ateliers
    path: src/data/ateliers.json
    type: file
    format: json
    fields:
      - name: heroTitle
        label: Titre principal
        type: string
      - name: heroSubtitle
        label: Sous-titre
        type: string
      - name: intro
        label: Introduction
        type: text
      - name: workshops
        label: Ateliers
        type: object
        list: true
        fields:
          - name: title
            label: Titre
            type: string
          - name: description
            label: Description
            type: text
      - name: formats
        label: Formats
        type: object
        list: true
        fields:
          - name: title
            label: Titre
            type: string
          - name: description
            label: Description
            type: text
          - name: price
            label: Prix
            type: string
      - name: ctaText
        label: Texte d'appel à l'action
        type: string
      - name: contactPhone
        label: Téléphone de contact
        type: string
      - name: contactEmail
        label: Email de contact
        type: string
      - name: pdfUrl
        label: URL du PDF
        type: string
      - name: outro
        label: Texte de conclusion
        type: text
