media: public/images
content:
 - name: carte
   label: Carte
   path: data/carte.json
   type: file
   fields:
    - name: product
      label: Banner
      type: object
      list: true
      fileds:
       - name: id
         type: number
       - name: title
         type: string
       - name: prix
         type: number
       - name: poids
         type: number
       - name: description
         type: string
         #images
       - name: category
         type: string
       - name: visible
         type: boolean